//! JS-side `Error.stack` capture via `wasm-bindgen`.

use std::panic::{self, PanicHookInfo};

use wasm_bindgen::prelude::*;

use crate::Frame;
use crate::namesec::BackfillNames;

#[wasm_bindgen(inline_js = r#"
export function __wacks_capture_stack() { return new Error().stack || ''; }
"#)]
extern "C" {
    #[wasm_bindgen(js_name = "__wacks_capture_stack")]
    fn capture_stack() -> String;
}

/// Configures and installs a WASM panic hook.
///
/// ```rust,ignore
/// wacks::Builder::new()
///     .framemap(include_bytes!("app.framemap"))
///     .install(|frames, info| {
///         // forward to your error reporter …
///     });
/// ```
pub struct Builder {
    framemap_data: Option<Vec<u8>>,
}

impl Builder {
    /// Provide a framemap for byte offset and source location resolution.
    ///
    /// The framemap is generated by `framemap-gen` from a WASM binary with
    /// DWARF debug info. It enables:
    /// - WebKit byte offset resolution (function index → byte offset)
    /// - Source location resolution (byte offset → filename, line, col)
    pub fn framemap(mut self, data: &[u8]) -> Self {
        self.framemap_data = Some(data.to_vec());
        self
    }

    /// Install the panic hook with the given callback.
    ///
    /// Consumes the builder, initializes the framemap (if provided),
    /// and installs a [`std::panic::set_hook`] that captures structured
    /// frames and passes them to `callback`.
    pub fn install(self, callback: fn(Vec<Frame>, &PanicHookInfo<'_>)) {
        if let Some(data) = self.framemap_data {
            crate::framemap::init(&data);
        }

        panic::set_hook(Box::new(move |info| {
            let stack = capture_stack();

            let mut frames = Frame::parse(&stack);

            frames.backfill_names();
            crate::framemap::resolve(&mut frames);

            callback(frames, info);
        }));
    }

    pub fn new() -> Self {
        Self {
            framemap_data: None,
        }
    }
}
