//! Runtime framemap resolver.
//!
//! Parses a framemap (generated by `framemap-gen`) to backfill
//! `wasm_byte_offset` on WebKit frames and resolve DWARF source locations
//! (`filename`, `lineno`, `colno`) on all WASM frames.

use std::cell::OnceCell;

use postcard::from_bytes;
use serde::{Deserialize, Serialize};

use crate::Frame;

/// Call site entry: a direct `call` instruction within a WASM function.
#[derive(Deserialize, Serialize)]
pub(crate) struct CallSite {
    pub(crate) caller: u32,
    pub(crate) callee: u32,
    pub(crate) offset: u64,
}

/// DWARF line entry: byte offset → source location.
#[derive(Deserialize, Serialize)]
pub(crate) struct LineEntry {
    pub(crate) addr: u64,
    pub(crate) source_idx: u32,
    pub(crate) line: u32,
    pub(crate) col: u32,
}

/// Serialized framemap format (must match `framemap_gen::Framemap`).
#[derive(Deserialize, Serialize)]
struct RawFramemap {
    num_imports: u32,
    function_starts: Vec<u64>,
    call_sites: Vec<CallSite>,
    sources: Vec<String>,
    line_entries: Vec<LineEntry>,
}

/// Parsed framemap optimized for runtime lookups.
pub(crate) struct ResolvedFramemap {
    num_imports: u32,
    function_starts: Vec<u64>,
    /// (caller, callee) → list of call-site byte offsets, sorted by key.
    call_sites: Vec<((u32, u32), Vec<u64>)>,
    /// DWARF line entries sorted by address for binary search.
    line_entries: Vec<LineEntry>,
    /// Source file paths indexed by `LineEntry::source_idx`.
    sources: Vec<String>,
}

thread_local! {
    static FRAMEMAP: OnceCell<ResolvedFramemap> = const { OnceCell::new() };
}

/// Store framemap bytes for runtime resolution.
pub(crate) fn init(data: &[u8]) {
    FRAMEMAP.with(|cell| {
        let _ = cell.set(ResolvedFramemap::new(data));
    });
}

/// Backfill byte offsets and resolve source locations from the framemap.
pub(crate) fn resolve(frames: &mut [Frame]) {
    FRAMEMAP.with(|cell| {
        if let Some(fm) = cell.get() {
            fm.resolve(frames);
            fm.resolve_source_locations(frames);
        }
    });
}

impl ResolvedFramemap {
    pub(crate) fn new(data: &[u8]) -> Self {
        let Ok(raw) = from_bytes::<RawFramemap>(data) else {
            return Self {
                num_imports: 0,
                call_sites: Vec::new(),
                function_starts: Vec::new(),
                line_entries: Vec::new(),
                sources: Vec::new(),
            };
        };

        let mut call_sites: Vec<((u32, u32), Vec<u64>)> = Vec::new();
        for site in raw.call_sites {
            let key = (site.caller, site.callee);
            match call_sites.binary_search_by_key(&key, |(k, _)| *k) {
                Ok(i) => call_sites[i].1.push(site.offset),
                Err(i) => call_sites.insert(i, (key, vec![site.offset])),
            }
        }

        Self {
            num_imports: raw.num_imports,
            function_starts: raw.function_starts,
            call_sites,
            sources: raw.sources,
            line_entries: raw.line_entries,
        }
    }

    fn function_start(&self, index: u32) -> Option<&u64> {
        self.function_starts
            .get(index.checked_sub(self.num_imports)? as usize)
    }

    /// Resolve byte offsets for frames using adjacent-pair call-site lookups.
    pub(crate) fn resolve(&self, frames: &mut [Frame]) {
        for i in 0..frames.len() {
            if frames[i].wasm_byte_offset.is_some() || frames[i].wasm_function_index.is_none() {
                continue;
            }

            let caller = frames[i].wasm_function_index.unwrap();

            if i > 0 {
                if let Some(callee) = frames[i - 1].wasm_function_index {
                    let key = (caller, callee);
                    if let Ok(idx) = self.call_sites.binary_search_by_key(&key, |(k, _)| *k) {
                        frames[i].wasm_byte_offset = Some(self.call_sites[idx].1[0]);
                        continue;
                    }
                }
            }

            if let Some(&offset) = self.function_start(caller) {
                frames[i].wasm_byte_offset = Some(offset);
            }
        }
    }

    /// Resolve source locations for WASM frames using DWARF line entries.
    ///
    /// For each frame with a `wasm_byte_offset`, binary searches the line
    /// entries to find the entry with the largest address ≤ the byte offset,
    /// then populates `filename`, `lineno`, and `colno`.
    pub(crate) fn resolve_source_locations(&self, frames: &mut [Frame]) {
        if self.line_entries.is_empty() {
            return;
        }

        for frame in frames.iter_mut() {
            let Some(offset) = frame.wasm_byte_offset else {
                continue;
            };

            let idx = match self.line_entries.binary_search_by_key(&offset, |e| e.addr) {
                Ok(i) => i,
                Err(0) => continue,
                Err(i) => i - 1,
            };

            let entry = &self.line_entries[idx];
            if let Some(source) = self.sources.get(entry.source_idx as usize) {
                frame.filename = Some(source.clone());
                frame.lineno = Some(entry.line);
                frame.colno = Some(entry.col);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_frame(function_index: Option<u32>, byte_offset: Option<u64>) -> Frame {
        Frame {
            colno: None,
            filename: None,
            function: None,
            in_app: false,
            lineno: None,
            raw_function: None,
            wasm_byte_offset: byte_offset,
            wasm_function_index: function_index,
        }
    }

    fn make_framemap_with_lines() -> ResolvedFramemap {
        let raw = RawFramemap {
            num_imports: 0,
            function_starts: vec![100, 200],
            call_sites: vec![],
            sources: vec!["src/lib.rs".into(), "src/main.rs".into()],
            line_entries: vec![
                LineEntry {
                    addr: 100,
                    source_idx: 0,
                    line: 10,
                    col: 5,
                },
                LineEntry {
                    addr: 150,
                    source_idx: 0,
                    line: 15,
                    col: 9,
                },
                LineEntry {
                    addr: 200,
                    source_idx: 1,
                    line: 42,
                    col: 1,
                },
            ],
        };
        let data = postcard::to_allocvec(&raw).unwrap();
        ResolvedFramemap::new(&data)
    }

    #[test]
    fn empty_data_does_not_panic() {
        let fm = ResolvedFramemap::new(&[]);
        assert!(fm.function_starts.is_empty());
        assert!(fm.call_sites.is_empty());
        assert!(fm.sources.is_empty());
        assert!(fm.line_entries.is_empty());
    }

    #[test]
    fn resolves_unambiguous_call_site() {
        let raw = RawFramemap {
            num_imports: 2,
            function_starts: vec![100, 200, 300],
            call_sites: vec![CallSite {
                caller: 3,
                callee: 4,
                offset: 210,
            }],
            sources: vec![],
            line_entries: vec![],
        };
        let data = postcard::to_allocvec(&raw).unwrap();
        let fm = ResolvedFramemap::new(&data);

        // Stack: [callee=4, caller=3] (index 0 is top of stack)
        let mut frames = vec![make_frame(Some(4), None), make_frame(Some(3), None)];

        fm.resolve(&mut frames);

        // Caller (frame 1) should get the exact call-site offset
        assert_eq!(frames[1].wasm_byte_offset, Some(210));
        // Callee (frame 0) has no caller above it, falls back to function start
        assert_eq!(frames[0].wasm_byte_offset, Some(300));
    }

    #[test]
    fn skips_frames_with_existing_offset() {
        let raw = RawFramemap {
            num_imports: 0,
            function_starts: vec![100],
            call_sites: vec![],
            sources: vec![],
            line_entries: vec![],
        };
        let data = postcard::to_allocvec(&raw).unwrap();
        let fm = ResolvedFramemap::new(&data);

        let mut frames = vec![make_frame(Some(0), Some(999))];
        fm.resolve(&mut frames);

        assert_eq!(frames[0].wasm_byte_offset, Some(999));
    }

    #[test]
    fn ambiguous_uses_first_call_site() {
        let raw = RawFramemap {
            num_imports: 0,
            function_starts: vec![100, 200],
            call_sites: vec![
                CallSite {
                    caller: 0,
                    callee: 1,
                    offset: 110,
                },
                CallSite {
                    caller: 0,
                    callee: 1,
                    offset: 140,
                },
            ],
            sources: vec![],
            line_entries: vec![],
        };
        let data = postcard::to_allocvec(&raw).unwrap();
        let fm = ResolvedFramemap::new(&data);

        let mut frames = vec![make_frame(Some(1), None), make_frame(Some(0), None)];
        fm.resolve(&mut frames);

        assert_eq!(frames[1].wasm_byte_offset, Some(110));
    }

    #[test]
    fn resolve_source_exact_match() {
        let fm = make_framemap_with_lines();
        let mut frames = vec![make_frame(Some(0), Some(100))];

        fm.resolve_source_locations(&mut frames);

        assert_eq!(frames[0].filename.as_deref(), Some("src/lib.rs"));
        assert_eq!(frames[0].lineno, Some(10));
        assert_eq!(frames[0].colno, Some(5));
    }

    #[test]
    fn resolve_source_between_entries() {
        let fm = make_framemap_with_lines();
        let mut frames = vec![make_frame(Some(0), Some(130))];

        fm.resolve_source_locations(&mut frames);

        assert_eq!(frames[0].filename.as_deref(), Some("src/lib.rs"));
        assert_eq!(frames[0].lineno, Some(10));
        assert_eq!(frames[0].colno, Some(5));
    }

    #[test]
    fn resolve_source_skips_without_offset() {
        let fm = make_framemap_with_lines();
        let mut frames = vec![make_frame(Some(0), None)];

        fm.resolve_source_locations(&mut frames);

        assert!(frames[0].filename.is_none());
    }

    #[test]
    fn resolve_source_before_first_entry() {
        let fm = make_framemap_with_lines();
        let mut frames = vec![make_frame(Some(0), Some(50))];

        fm.resolve_source_locations(&mut frames);

        assert!(frames[0].filename.is_none());
    }

    #[test]
    fn resolve_source_empty_line_entries() {
        let fm = ResolvedFramemap::new(&[]);
        let mut frames = vec![make_frame(Some(0), Some(100))];

        fm.resolve_source_locations(&mut frames);

        assert!(frames[0].filename.is_none());
    }
}
