//! Runtime framemap resolver for WebKit byte offset backfill.
//!
//! Parses a framemap (generated by `framemap-gen`) and backfills
//! `wasm_byte_offset` on frames that only have `wasm_function_index`
//! (WebKit). Uses the call-site index for exact resolution when the
//! `(caller, callee)` pair is unambiguous, falling back to function-start
//! offsets otherwise.

use std::cell::OnceCell;
use std::collections::HashMap;

use postcard::from_bytes;
use serde::{Deserialize, Serialize};

use crate::Frame;

#[cfg(target_arch = "wasm32")]
pub(crate) trait BackfillByteOffsets {
    fn backfill_byte_offsets(&mut self);
}

/// Call site entry: a direct `call` instruction within a WASM function.
#[derive(Deserialize, Serialize)]
pub(crate) struct CallSite {
    pub(crate) caller: u32,
    pub(crate) callee: u32,
    pub(crate) offset: u64,
}

/// Serialized framemap format (must match `framemap_gen::Framemap`).
#[derive(Deserialize, Serialize)]
struct RawFramemap {
    num_imports: u32,
    function_starts: Vec<u64>,
    call_sites: Vec<CallSite>,
}

/// Parsed framemap optimized for runtime lookups.
pub(crate) struct ResolvedFramemap {
    function_starts: HashMap<u32, u64>,
    /// (caller, callee) → list of call-site byte offsets.
    call_sites: HashMap<(u32, u32), Vec<u64>>,
}

impl ResolvedFramemap {
    pub(crate) fn new(data: &[u8]) -> Self {
        let Ok(raw) = from_bytes::<RawFramemap>(data) else {
            return Self {
                function_starts: HashMap::new(),
                call_sites: HashMap::new(),
            };
        };

        let mut function_starts = HashMap::with_capacity(raw.function_starts.len());
        for (i, &offset) in raw.function_starts.iter().enumerate() {
            function_starts.insert(raw.num_imports + i as u32, offset);
        }

        let mut call_sites: HashMap<(u32, u32), Vec<u64>> = HashMap::new();
        for site in raw.call_sites {
            call_sites
                .entry((site.caller, site.callee))
                .or_default()
                .push(site.offset);
        }

        Self { function_starts, call_sites }
    }

    /// Resolve byte offsets for frames using adjacent-pair call-site lookups.
    pub(crate) fn resolve(&self, frames: &mut [Frame]) {
        for i in 0..frames.len() {
            if frames[i].wasm_byte_offset.is_some() || frames[i].wasm_function_index.is_none() {
                continue;
            }

            let caller = frames[i].wasm_function_index.unwrap();

            if i > 0 {
                if let Some(callee) = frames[i - 1].wasm_function_index {
                    if let Some(offsets) = self.call_sites.get(&(caller, callee)) {
                        frames[i].wasm_byte_offset = Some(offsets[0]);
                        continue;
                    }
                }
            }

            if let Some(&offset) = self.function_starts.get(&caller) {
                frames[i].wasm_byte_offset = Some(offset);
            }
        }
    }
}

#[cfg(target_arch = "wasm32")]
impl BackfillByteOffsets for [Frame] {
    fn backfill_byte_offsets(&mut self) {
        FRAMEMAP.with(|cell| {
            if let Some(fm) = cell.get() {
                fm.resolve(self);
            }
        });
    }
}

thread_local! {
    static FRAMEMAP: OnceCell<ResolvedFramemap> = const { OnceCell::new() };
}

/// Store framemap bytes for runtime resolution.
pub(crate) fn init(data: &[u8]) {
    FRAMEMAP.with(|cell| {
        let _ = cell.set(ResolvedFramemap::new(data));
    });
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_frame(function_index: Option<u32>, byte_offset: Option<u64>) -> Frame {
        Frame {
            colno: None,
            filename: None,
            function: None,
            in_app: false,
            lineno: None,
            raw_function: None,
            wasm_byte_offset: byte_offset,
            wasm_function_index: function_index,
        }
    }

    #[test]
    fn empty_data_does_not_panic() {
        let fm = ResolvedFramemap::new(&[]);
        assert!(fm.function_starts.is_empty());
        assert!(fm.call_sites.is_empty());
    }

    #[test]
    fn resolves_unambiguous_call_site() {
        let raw = RawFramemap {
            num_imports: 2,
            function_starts: vec![100, 200, 300],
            call_sites: vec![
                CallSite { caller: 3, callee: 4, offset: 210 },
            ],
        };
        let data = postcard::to_allocvec(&raw).unwrap();
        let fm = ResolvedFramemap::new(&data);

        // Stack: [callee=4, caller=3] (index 0 is top of stack)
        let mut frames = vec![
            make_frame(Some(4), None),
            make_frame(Some(3), None),
        ];

        fm.resolve(&mut frames);

        // Caller (frame 1) should get the exact call-site offset
        assert_eq!(frames[1].wasm_byte_offset, Some(210));
        // Callee (frame 0) has no caller above it, falls back to function start
        assert_eq!(frames[0].wasm_byte_offset, Some(300));
    }

    #[test]
    fn skips_frames_with_existing_offset() {
        let raw = RawFramemap {
            num_imports: 0,
            function_starts: vec![100],
            call_sites: vec![],
        };
        let data = postcard::to_allocvec(&raw).unwrap();
        let fm = ResolvedFramemap::new(&data);

        let mut frames = vec![make_frame(Some(0), Some(999))];
        fm.resolve(&mut frames);

        assert_eq!(frames[0].wasm_byte_offset, Some(999));
    }

    #[test]
    fn ambiguous_uses_first_call_site() {
        let raw = RawFramemap {
            num_imports: 0,
            function_starts: vec![100, 200],
            call_sites: vec![
                CallSite { caller: 0, callee: 1, offset: 110 },
                CallSite { caller: 0, callee: 1, offset: 140 },
            ],
        };
        let data = postcard::to_allocvec(&raw).unwrap();
        let fm = ResolvedFramemap::new(&data);

        let mut frames = vec![
            make_frame(Some(1), None),
            make_frame(Some(0), None),
        ];
        fm.resolve(&mut frames);

        assert_eq!(frames[1].wasm_byte_offset, Some(110));
    }
}
