//! Source map v3 parser for WASM byte-offset → source location resolution.

use serde_json::Value;

struct Mapping {
    gen_col: u32,
    src_idx: u32,
    src_line: u32,
    src_col: u32,
}

/// Parsed source map with lookup by generated byte offset.
pub(crate) struct SourceMap {
    sources: Vec<String>,
    mappings: Vec<Mapping>,
}

impl Mapping {
    /// Decode VLQ-encoded source map v3 mappings.
    fn decode_all(mappings: &str) -> Option<Vec<Self>> {
        let mut result = Vec::new();
        let mut src_idx: i64 = 0;
        let mut src_line: i64 = 0;
        let mut src_col: i64 = 0;

        for group in mappings.split(';') {
            let mut gen_col: i64 = 0;

            for segment in group.split(',') {
                if segment.is_empty() {
                    continue;
                }

                let mut iter = segment.bytes().peekable();
                gen_col += vlq::decode(&mut iter).ok()?;

                if iter.peek().is_none() {
                    continue;
                }

                src_idx += vlq::decode(&mut iter).ok()?;
                src_line += vlq::decode(&mut iter).ok()?;
                src_col += vlq::decode(&mut iter).ok()?;

                result.push(Self {
                    gen_col: u32::try_from(gen_col).ok()?,
                    src_idx: u32::try_from(src_idx).ok()?,
                    src_line: u32::try_from(src_line).ok()?,
                    src_col: u32::try_from(src_col).ok()?,
                });
            }
        }

        Some(result)
    }
}

impl SourceMap {
    /// Parse a source map v3 JSON string.
    pub(crate) fn new(json: &str) -> Option<Self> {
        let mut v: Value = serde_json::from_str(json).ok()?;
        let sources = serde_json::from_value(v["sources"].take()).ok()?;
        let mappings = Mapping::decode_all(v["mappings"].as_str()?)?;
        Some(Self { sources, mappings })
    }

    /// Resolve a WASM byte offset to `(file, line, col)` (1-indexed).
    pub(crate) fn resolve(&self, byte_offset: u64) -> Option<(&str, u32, u32)> {
        let offset = u32::try_from(byte_offset).ok()?;
        let idx = self.mappings.partition_point(|m| m.gen_col <= offset);
        let m = self.mappings.get(idx.checked_sub(1)?)?;
        let file = self.sources.get(m.src_idx as usize)?;
        Some((file, m.src_line + 1, m.src_col + 1))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn source_map_json(sources: &[&str], mappings: &str) -> String {
        let sources: Vec<String> = sources.iter().map(|s| format!("\"{s}\"")).collect();
        format!(
            r#"{{"version":3,"sources":[{}],"mappings":"{mappings}"}}"#,
            sources.join(","),
        )
    }

    #[test]
    fn parse_single_mapping() {
        let json = source_map_json(&["src/lib.rs"], "AAAA");
        let sm = SourceMap::new(&json).unwrap();

        assert_eq!(sm.sources, vec!["src/lib.rs"]);
        assert_eq!(sm.mappings.len(), 1);
        assert_eq!(sm.mappings[0].gen_col, 0);
    }

    #[test]
    fn parse_multiple_mappings() {
        // AACA = gen_col+0, src_idx+0, src_line+1, src_col+0
        // EAAE = gen_col+2, src_idx+0, src_line+0, src_col+2
        // ICCI = gen_col+4, src_idx+1, src_line+1, src_col+4
        let json = source_map_json(&["src/lib.rs", "src/main.rs"], "AACA,EAAE,ICCI");
        let sm = SourceMap::new(&json).unwrap();

        assert_eq!(sm.mappings.len(), 3);
        assert_eq!(sm.mappings[0].gen_col, 0);
        assert_eq!(sm.mappings[0].src_line, 1);
        assert_eq!(sm.mappings[1].gen_col, 2);
        assert_eq!(sm.mappings[1].src_col, 2);
        assert_eq!(sm.mappings[2].gen_col, 6);
        assert_eq!(sm.mappings[2].src_idx, 1);
    }

    #[test]
    fn resolve_exact_offset() {
        let json = source_map_json(&["src/lib.rs"], "AACA,EAAE");
        let sm = SourceMap::new(&json).unwrap();

        let (file, line, col) = sm.resolve(0).unwrap();
        assert_eq!(file, "src/lib.rs");
        assert_eq!(line, 2); // 0-indexed 1 → 1-indexed 2
        assert_eq!(col, 1);

        let (_, line, col) = sm.resolve(2).unwrap();
        assert_eq!(line, 2);
        assert_eq!(col, 3); // 0-indexed 2 → 1-indexed 3
    }

    #[test]
    fn resolve_between_offsets() {
        let json = source_map_json(&["a.rs"], "AAAA,IAAA");
        let sm = SourceMap::new(&json).unwrap();

        // Offset 1 falls between gen_col=0 and gen_col=4 → resolves to first
        let (_, line, _) = sm.resolve(1).unwrap();
        assert_eq!(line, 1);

        // Offset 100 past last mapping → resolves to last
        assert!(sm.resolve(100).is_some());
    }

    #[test]
    fn resolve_before_first_mapping() {
        // First mapping at gen_col=2 (E = delta +2)
        let json = source_map_json(&["a.rs"], "EAAA");
        let sm = SourceMap::new(&json).unwrap();
        assert!(sm.resolve(0).is_none());
        assert!(sm.resolve(1).is_none());
        assert!(sm.resolve(2).is_some());
    }

    #[test]
    fn skips_one_field_segments() {
        // "A" is a 1-field segment (gen_col only), no source mapping
        let json = source_map_json(&["a.rs"], "A,EAAA");
        let sm = SourceMap::new(&json).unwrap();

        assert_eq!(sm.mappings.len(), 1);
        assert_eq!(sm.mappings[0].gen_col, 2);
    }

    #[test]
    fn empty_and_malformed_input() {
        assert!(SourceMap::new("").is_none());
        assert!(SourceMap::new("not json").is_none());
        assert!(SourceMap::new("{}").is_none());
        assert!(SourceMap::new(r#"{"sources":[],"mappings":""}"#).is_some());
    }
}
